// Indonesian Regions Data (Wilayah Indonesia)
// Source: Various public APIs

export const provinces = [
    { id: "11", name: "Aceh" },
    { id: "51", name: "Bali" },
    { id: "19", name: "Bangka Belitung" },
    { id: "36", name: "Banten" },
    { id: "17", name: "Bengkulu" },
    { id: "34", name: "Daerah Istimewa Yogyakarta" },
    { id: "31", name: "DKI Jakarta" },
    { id: "75", name: "Gorontalo" },
    { id: "15", name: "Jambi" },
    { id: "32", name: "Jawa Barat" },
    { id: "33", name: "Jawa Tengah" },
    { id: "35", name: "Jawa Timur" },
    { id: "61", name: "Kalimantan Barat" },
    { id: "63", name: "Kalimantan Selatan" },
    { id: "62", name: "Kalimantan Tengah" },
    { id: "64", name: "Kalimantan Timur" },
    { id: "65", name: "Kalimantan Utara" },
    { id: "21", name: "Kepulauan Riau" },
    { id: "18", name: "Lampung" },
    { id: "81", name: "Maluku" },
    { id: "82", name: "Maluku Utara" },
    { id: "52", name: "Nusa Tenggara Barat" },
    { id: "53", name: "Nusa Tenggara Timur" },
    { id: "94", name: "Papua" },
    { id: "91", name: "Papua Barat" },
    { id: "14", name: "Riau" },
    { id: "76", name: "Sulawesi Barat" },
    { id: "73", name: "Sulawesi Selatan" },
    { id: "72", name: "Sulawesi Tengah" },
    { id: "74", name: "Sulawesi Tenggara" },
    { id: "71", name: "Sulawesi Utara" },
    { id: "13", name: "Sumatera Barat" },
    { id: "16", name: "Sumatera Selatan" },
    { id: "12", name: "Sumatera Utara" },
];

// Sample cities/regencies for each province (most common ones)
export const cities: Record<string, { id: string; name: string; province_id: string }[]> = {
    "11": [ // Aceh
        { id: "1101", name: "Kabupaten Aceh Selatan", province_id: "11" },
        { id: "1102", name: "Kabupaten Aceh Tenggara", province_id: "11" },
        { id: "1103", name: "Kabupaten Aceh Timur", province_id: "11" },
        { id: "1104", name: "Kabupaten Aceh Tengah", province_id: "11" },
        { id: "1105", name: "Kabupaten Aceh Barat", province_id: "11" },
        { id: "1106", name: "Kabupaten Aceh Besar", province_id: "11" },
        { id: "1107", name: "Kabupaten Pidie", province_id: "11" },
        { id: "1108", name: "Kabupaten Bireuen", province_id: "11" },
        { id: "1109", name: "Kabupaten Aceh Singkil", province_id: "11" },
        { id: "1110", name: "Kabupaten Simeulue", province_id: "11" },
        { id: "1111", name: "Kabupaten Aceh Jaya", province_id: "11" },
        { id: "1112", name: "Kabupaten Nagan Raya", province_id: "11" },
        { id: "1113", name: "Kabupaten Aceh Tamiang", province_id: "11" },
        { id: "1114", name: "Kabupaten Bener Meriah", province_id: "11" },
        { id: "1115", name: "Kabupaten Pidie Jaya", province_id: "11" },
        { id: "1116", name: "Kabupaten Aceh Barat Daya", province_id: "11" },
        { id: "1117", name: "Kabupaten Gayo Lues", province_id: "11" },
        { id: "1171", name: "Kota Banda Aceh", province_id: "11" },
        { id: "1172", name: "Kota Sabang", province_id: "11" },
        { id: "1173", name: "Kota Langsa", province_id: "11" },
        { id: "1174", name: "Kota Lhokseumawe", province_id: "11" },
        { id: "1175", name: "Kota Subulussalam", province_id: "11" },
    ],
    "31": [ // DKI Jakarta
        { id: "3101", name: "Kabupaten Kepulauan Seribu", province_id: "31" },
        { id: "3171", name: "Kota Jakarta Selatan", province_id: "31" },
        { id: "3172", name: "Kota Jakarta Timur", province_id: "31" },
        { id: "3173", name: "Kota Jakarta Pusat", province_id: "31" },
        { id: "3174", name: "Kota Jakarta Barat", province_id: "31" },
        { id: "3175", name: "Kota Jakarta Utara", province_id: "31" },
    ],
    "32": [ // Jawa Barat
        { id: "3201", name: "Kabupaten Bogor", province_id: "32" },
        { id: "3202", name: "Kabupaten Sukabumi", province_id: "32" },
        { id: "3203", name: "Kabupaten Cianjur", province_id: "32" },
        { id: "3204", name: "Kabupaten Bandung", province_id: "32" },
        { id: "3205", name: "Kabupaten Garut", province_id: "32" },
        { id: "3206", name: "Kabupaten Tasikmalaya", province_id: "32" },
        { id: "3207", name: "Kabupaten Ciamis", province_id: "32" },
        { id: "3208", name: "Kabupaten Kuningan", province_id: "32" },
        { id: "3209", name: "Kabupaten Cirebon", province_id: "32" },
        { id: "3210", name: "Kabupaten Majalengka", province_id: "32" },
        { id: "3211", name: "Kabupaten Sumedang", province_id: "32" },
        { id: "3212", name: "Kabupaten Indramayu", province_id: "32" },
        { id: "3213", name: "Kabupaten Subang", province_id: "32" },
        { id: "3214", name: "Kabupaten Purwakarta", province_id: "32" },
        { id: "3215", name: "Kabupaten Karawang", province_id: "32" },
        { id: "3216", name: "Kabupaten Bekasi", province_id: "32" },
        { id: "3217", name: "Kabupaten Bandung Barat", province_id: "32" },
        { id: "3218", name: "Kabupaten Pangandaran", province_id: "32" },
        { id: "3271", name: "Kota Bogor", province_id: "32" },
        { id: "3272", name: "Kota Sukabumi", province_id: "32" },
        { id: "3273", name: "Kota Bandung", province_id: "32" },
        { id: "3274", name: "Kota Cirebon", province_id: "32" },
        { id: "3275", name: "Kota Bekasi", province_id: "32" },
        { id: "3276", name: "Kota Depok", province_id: "32" },
        { id: "3277", name: "Kota Cimahi", province_id: "32" },
        { id: "3278", name: "Kota Tasikmalaya", province_id: "32" },
        { id: "3279", name: "Kota Banjar", province_id: "32" },
    ],
    "33": [ // Jawa Tengah
        { id: "3301", name: "Kabupaten Cilacap", province_id: "33" },
        { id: "3302", name: "Kabupaten Banyumas", province_id: "33" },
        { id: "3303", name: "Kabupaten Purbalingga", province_id: "33" },
        { id: "3304", name: "Kabupaten Banjarnegara", province_id: "33" },
        { id: "3305", name: "Kabupaten Kebumen", province_id: "33" },
        { id: "3306", name: "Kabupaten Purworejo", province_id: "33" },
        { id: "3307", name: "Kabupaten Wonosobo", province_id: "33" },
        { id: "3308", name: "Kabupaten Magelang", province_id: "33" },
        { id: "3309", name: "Kabupaten Boyolali", province_id: "33" },
        { id: "3310", name: "Kabupaten Klaten", province_id: "33" },
        { id: "3311", name: "Kabupaten Sukoharjo", province_id: "33" },
        { id: "3312", name: "Kabupaten Wonogiri", province_id: "33" },
        { id: "3313", name: "Kabupaten Karanganyar", province_id: "33" },
        { id: "3314", name: "Kabupaten Sragen", province_id: "33" },
        { id: "3315", name: "Kabupaten Grobogan", province_id: "33" },
        { id: "3316", name: "Kabupaten Blora", province_id: "33" },
        { id: "3317", name: "Kabupaten Rembang", province_id: "33" },
        { id: "3318", name: "Kabupaten Pati", province_id: "33" },
        { id: "3319", name: "Kabupaten Kudus", province_id: "33" },
        { id: "3320", name: "Kabupaten Jepara", province_id: "33" },
        { id: "3321", name: "Kabupaten Demak", province_id: "33" },
        { id: "3322", name: "Kabupaten Semarang", province_id: "33" },
        { id: "3323", name: "Kabupaten Temanggung", province_id: "33" },
        { id: "3324", name: "Kabupaten Kendal", province_id: "33" },
        { id: "3325", name: "Kabupaten Batang", province_id: "33" },
        { id: "3326", name: "Kabupaten Pekalongan", province_id: "33" },
        { id: "3327", name: "Kabupaten Pemalang", province_id: "33" },
        { id: "3328", name: "Kabupaten Tegal", province_id: "33" },
        { id: "3329", name: "Kabupaten Brebes", province_id: "33" },
        { id: "3371", name: "Kota Magelang", province_id: "33" },
        { id: "3372", name: "Kota Surakarta", province_id: "33" },
        { id: "3373", name: "Kota Salatiga", province_id: "33" },
        { id: "3374", name: "Kota Semarang", province_id: "33" },
        { id: "3375", name: "Kota Pekalongan", province_id: "33" },
        { id: "3376", name: "Kota Tegal", province_id: "33" },
    ],
    "35": [ // Jawa Timur
        { id: "3501", name: "Kabupaten Pacitan", province_id: "35" },
        { id: "3502", name: "Kabupaten Ponorogo", province_id: "35" },
        { id: "3503", name: "Kabupaten Trenggalek", province_id: "35" },
        { id: "3504", name: "Kabupaten Tulungagung", province_id: "35" },
        { id: "3505", name: "Kabupaten Blitar", province_id: "35" },
        { id: "3506", name: "Kabupaten Kediri", province_id: "35" },
        { id: "3507", name: "Kabupaten Malang", province_id: "35" },
        { id: "3508", name: "Kabupaten Lumajang", province_id: "35" },
        { id: "3509", name: "Kabupaten Jember", province_id: "35" },
        { id: "3510", name: "Kabupaten Banyuwangi", province_id: "35" },
        { id: "3511", name: "Kabupaten Bondowoso", province_id: "35" },
        { id: "3512", name: "Kabupaten Situbondo", province_id: "35" },
        { id: "3513", name: "Kabupaten Probolinggo", province_id: "35" },
        { id: "3514", name: "Kabupaten Pasuruan", province_id: "35" },
        { id: "3515", name: "Kabupaten Sidoarjo", province_id: "35" },
        { id: "3516", name: "Kabupaten Mojokerto", province_id: "35" },
        { id: "3517", name: "Kabupaten Jombang", province_id: "35" },
        { id: "3518", name: "Kabupaten Nganjuk", province_id: "35" },
        { id: "3519", name: "Kabupaten Madiun", province_id: "35" },
        { id: "3520", name: "Kabupaten Magetan", province_id: "35" },
        { id: "3521", name: "Kabupaten Ngawi", province_id: "35" },
        { id: "3522", name: "Kabupaten Bojonegoro", province_id: "35" },
        { id: "3523", name: "Kabupaten Tuban", province_id: "35" },
        { id: "3524", name: "Kabupaten Lamongan", province_id: "35" },
        { id: "3525", name: "Kabupaten Gresik", province_id: "35" },
        { id: "3526", name: "Kabupaten Bangkalan", province_id: "35" },
        { id: "3527", name: "Kabupaten Sampang", province_id: "35" },
        { id: "3528", name: "Kabupaten Pamekasan", province_id: "35" },
        { id: "3529", name: "Kabupaten Sumenep", province_id: "35" },
        { id: "3571", name: "Kota Kediri", province_id: "35" },
        { id: "3572", name: "Kota Blitar", province_id: "35" },
        { id: "3573", name: "Kota Malang", province_id: "35" },
        { id: "3574", name: "Kota Probolinggo", province_id: "35" },
        { id: "3575", name: "Kota Pasuruan", province_id: "35" },
        { id: "3576", name: "Kota Mojokerto", province_id: "35" },
        { id: "3577", name: "Kota Madiun", province_id: "35" },
        { id: "3578", name: "Kota Surabaya", province_id: "35" },
        { id: "3579", name: "Kota Batu", province_id: "35" },
    ],
    "51": [ // Bali
        { id: "5101", name: "Kabupaten Jembrana", province_id: "51" },
        { id: "5102", name: "Kabupaten Tabanan", province_id: "51" },
        { id: "5103", name: "Kabupaten Badung", province_id: "51" },
        { id: "5104", name: "Kabupaten Gianyar", province_id: "51" },
        { id: "5105", name: "Kabupaten Klungkung", province_id: "51" },
        { id: "5106", name: "Kabupaten Bangli", province_id: "51" },
        { id: "5107", name: "Kabupaten Karang Asem", province_id: "51" },
        { id: "5108", name: "Kabupaten Buleleng", province_id: "51" },
        { id: "5171", name: "Kota Denpasar", province_id: "51" },
    ],
};

// Sample districts for common cities (can be expanded)
export const districts: Record<string, { id: string; name: string; city_id: string }[]> = {
    "3303": [ // Purbalingga
        { id: "330301", name: "Kemangkon", city_id: "3303" },
        { id: "330302", name: "Bukateja", city_id: "3303" },
        { id: "330303", name: "Kejobong", city_id: "3303" },
        { id: "330304", name: "Kaligondang", city_id: "3303" },
        { id: "330305", name: "Purbalingga", city_id: "3303" },
        { id: "330306", name: "Purbalingga Utara", city_id: "3303" },
        { id: "330307", name: "Bobotsari", city_id: "3303" },
        { id: "330308", name: "Karangreja", city_id: "3303" },
        { id: "330309", name: "Kutasari", city_id: "3303" },
        { id: "330310", name: "Pengadegan", city_id: "3303" },
        { id: "330311", name: "Kalimanah", city_id: "3303" },
        { id: "330312", name: "Padamara", city_id: "3303" },
        { id: "330313", name: "Mrebet", city_id: "3303" },
        { id: "330314", name: "Bojongsari", city_id: "3303" },
        { id: "330315", name: "Karanganyar", city_id: "3303" },
        { id: "330316", name: "Karangjambu", city_id: "3303" },
        { id: "330317", name: "Karangmoncol", city_id: "3303" },
        { id: "330318", name: "Rembang", city_id: "3303" },
    ],
    "3171": [ // Jakarta Selatan
        { id: "317101", name: "Jagakarsa", city_id: "3171" },
        { id: "317102", name: "Pasar Minggu", city_id: "3171" },
        { id: "317103", name: "Cilandak", city_id: "3171" },
        { id: "317104", name: "Pesanggrahan", city_id: "3171" },
        { id: "317105", name: "Kebayoran Lama", city_id: "3171" },
        { id: "317106", name: "Kebayoran Baru", city_id: "3171" },
        { id: "317107", name: "Mampang Prapatan", city_id: "3171" },
        { id: "317108", name: "Pancoran", city_id: "3171" },
        { id: "317109", name: "Tebet", city_id: "3171" },
        { id: "317110", name: "Setiabudi", city_id: "3171" },
    ],
};
